server:
  port: 8085
spring:
  application:
    name: product-service
eureka:
  client:
    serviceUrl:
      #ohne docker
      #      defaultZone: http://localhost:8761/eureka/
      #docker
      # Dont know how this works but it works with the JVA-Env variable in the docker compose
      defaultZone: ${EUREKA_SERVER:http://eureka:8761/eureka}
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"
      #docker config
      hostname: eureka