server:
  port: 8091

spring:
  application:
    name: zuul
  cloud:
    config:
      enable: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    status-page-url-path: /info
    health-check-url-path: /health

zuul:
  ignored-services: '*' #hide all core and comp services by default
  routes:
    product:
      path: /product/**
      serviceId: product-service
      stripPrefix: false

    catalogue:
      path: /catalogue/**
      serviceId: catalogue-proxy
      stripPrefix: false

    category:
      path: /category/**
      serviceId: category-service
      stripPrefix: false

    account:
      path: /account/**
      serviceId: account-proxy
      stripPrefix: false

    user:
      path: /user/**
      serviceId: user-service
      stripPrefix: false

    role:
      path: /role/**
      serviceId: role-service
      stripPrefix: false
